#!/bin/bash

echo "Enter the username"
read username 


echo "Enter password"
read password

if [ -z "$username" ] || [ -z "$password" ]
then
        if [ -z "$username" ] && [ -z "$password" ]
        then
                echo "Both fields cannot be empty"
        elif [ -n "$username" ] && [ -z "$password" ]
        then
                echo "Password field cannot be empty"
        elif [ -z "$username" ] && [ -n "$password" ]
        then
                echo "Username field cannot be empty"
        else
                echo "Something wrong"
        fi
elif [ -n "$username" ] && [ -n "$password" ]
then
        if [ "$username" == "admin" ] && [ "$password" == "pass" ]
        then
                echo "Login succesfull"
        elif [ "$username" != "admin" ] || [ "$password" != "pass" ]
        then
                echo "Incorrect login"
                sleep 2
                echo "Still got three chances"
                echo "***********************************"
                chance=0
                while [ $chance -le 3 ]
                do
                        echo "*********************************"
                        echo "Enter username"
                        read username
                        echo "Enyer password" 
                        read password

                        if [ "$username" == "admin" ] && [ "$password" == "pass" ]
                        then
                                echo "Login succesfull"
                                break
                        else
                                echo "Login incorrect"
                                ((chance=chance+1))
                                continue
                        fi
                done
        fi
fi

----------------------------------------------------------------------------------------------------------------------------------------------------------------------


#!/bin/bash

hrishi () {
        echo "Enter username"
        read username 

        echo "Enter password"
        read password 
}
hrishi

if [ -z "$username" ] || [ -z "$password" ]
then
        if [ -z "$username" ] && [ -z "$password" ]
        then
                echo "Both field cannot be empty"
        elif [ -n "$username" ] || [ -z "$password" ]
        then
                echo "Password field cannot be empty"
        else
                echo "Username field cannot be empty"
        fi
elif [ -n "$username" ] && [ -n "$password" ]
then
        if [ "$username" == "admin" ] && [ "$password" == "pass" ]
        then
                echo "Login sucessfull"
        else
                count=1
                while [ "$username" != "admin" ] || [ "$password" != "pass" ] && [ $count -le 3 ]
                do
                        echo "Incorrect login details"
                        echo "Still got 3 tries more" 
                        ((count++))
                        echo "**********************************"
                        hrishi
                        if [ "$username" == "admin" ] && [ "$password" == "pass" ]
                        then
                                echo "Login sucessfull"
                        else
                                continue
                        fi
                done
        fi

else
        echo "Invalid input"
fi

