#!/bin/bash

echo "Enter the username"
read username 


echo "Enter password"
read password

if [ -z "$username" ] || [ -z "$password" ]
then
        if [ -z "$username" ] && [ -z "$password" ]
        then
                echo "Both fields cannot be empty"
        elif [ -n "$username" ] && [ -z "$password" ]
        then
                echo "Password field cannot be empty"
        elif [ -z "$username" ] && [ -n "$password" ]
        then
                echo "Username field cannot be empty"
        else
                echo "Something wrong"
        fi
elif [ -n "$username" ] && [ -n "$password" ]
then
        if [ "$username" == "admin" ] && [ "$password" == "pass" ]
        then
                echo "Login succesfull"
        elif [ "$username" != "admin" ] || [ "$password" != "pass" ]
        then
                echo "Incorrect login"
                sleep 2
                echo "Still got three chances"
                echo "***********************************"
                chance=0
                while [ $chance -le 3 ]
                do
                        echo "*********************************"
                        echo "Enter username"
                        read username
                        echo "Enyer password" 
                        read password

                        if [ "$username" == "admin" ] && [ "$password" == "pass" ]
                        then
                                echo "Login succesfull"
                                break
                        else
                                echo "Login incorrect"
                                ((chance=chance+1))
                                continue
                        fi
                done
        fi
fi
