#!/bin/bash 

echo "Enter the first number"
read first


echo "Enter the second number"
read second 

if [ -z "$first" ] || [ -z "$second" ]
then
        if [ -n "$first" ] && [ -z "$second" ]
        then
                echo "Second number is empty"
        elif [ -z "$first" ] && [ -n "$second" ]
        then
                echo "First number is empty"
        else
                echo "Both number is empty"
        fi
elif [ -n "$first" ] &&  [ -n "$second" ]
then
        echo "****************************************"
        echo "Choose from below the Operations:"
        echo "Press 1: for Addition"
        echo "Press 2: for Subtraction"
        echo "Press 3: for Multiplication"
        echo "Press 4: for Remainder"
        echo "Press 5: for Quotient"
        read option
        echo "****************************************"
        if [ $option == "1" ]
        then
                ans=$((first+second))
                echo "Addition of $first and $second is: $ans"
        elif [ $option == "2" ]
        then
                ans=$((first-second))
                echo "Addition of $first and $second is: $ans"
        elif [ $option == "3" ]
        then
                ans=$((first*second))
                echo "Multiplication of $first and $second is: $ans"
        elif [ $option == "4" ]
        then
                ans=$((first%second))
                echo "Remainder of $first and $second is: $ans"
        elif [ $option == "5" ]
        then
                ans=$((first/second))
                echo "Quotient of $first and $second is: $ans"
        fi
fi
