#!/bin/bash

#asking user input 
echo "Enter the path"
read path

#asking user input 
echo "Enter file name"
read file 

#Checking user input
if [ -z "$path" ] || [ -z "$file" ]
then
        if [ -n "$path" ] && [ -z "$file" ]
        then
                echo "File field cannot be empty"
        elif [ -z "$path" ] && [ -n "$file" ]
        then
                echo "File field cannot be empty"
        else
                echo "Both field cannot empty"
        fi
#asking user input 
elif [ -n "$path" ] && [ -n "$file" ]
then
        if [ -f "$path$file" ]                #to check its a file
        then
                echo "Its a file"
        elif [ -d "$path$file" ]             #to check its a directory
        then
                echo "Its a directory"
        elif [ -s "$path$file" ]             #File exit and its not empty
        then
                echo "Its a File exit and its not empty"
        else
                echo "Invalid file or path"
        fi

fi
