#!/bin/bash

hrishi()
{
echo "Enter the network"
read network 

echo "Enter the first host"
read first
echo "ENter second host"
read second
}

hrishi

if [ -z "$network" ] || [ -z "$first" ] || [ -z "$second" ]
then
        if [ -z "$network" ] && ([ -n "$first" ] && [ -n "$second" ])
        then
                echo "Network field cannot be empty"
        elif [ -z "$first" ] && ([ -n "$network" ] && [ -n "$second" ])
        then
                echo "first field cannot be empty"
        elif [ -z "$second" ] && ([ -n "$network" ] && [ -n "$first" ])
        then
                echo "second field cannot be empty"
        else
                echo "Fields cannot be left empty"
        fi
elif [ -n "$network" ] && [ -n "$first" ] && [ -n "$second" ]
then
        for ip in $(seq $first $second)
        do
                ping -c 1 $network.$ip | grep "64 bytes" | cut -d " " -f4 | sort -h | uniq & 2>/dev/null
        done
fi
------------------------------------------------------------------------------------------------------------------------------------------------
#!/bin/bash 

rm -rf /home/kali/bash-scripts/output 

echo "Enter the network portion: Example 192.1.1."
read network 

echo "Enter the host range: Part1"
read host1 

echo "Enter the host range: Part1"
read host2 

if [ -z "$network" ] || [ -z "$host1" ] || [ -z "$host2" ] 
then
        if [ \( -n "$network" -a -n "$host2" \) ]  && [ -z "$host1" ]
        then
                echo "host-1  is empty"
        elif [ \( -n "$network" -a -n "$host1" \) ]  && [ -z "$host2" ]
        then
                echo "host-2  is empty"
        elif [ \( -n "$host1" -a -n "$host2" \) ]  && [ -z "$network" ]
        then
                echo "Network portion is empty" 
        else
                echo "More field empty"
        fi
elif [ -n "$network" ] && [ -n "$host1" ] && [ -n "$host2" ]
then
        echo "*****************************"
        echo "Checking connectivity: $network$host1-$host2"
        for ip in $(seq $host1 $host2)
        do
        ping -c 1 $network$ip | grep -i "64 bytes" | cut -d " " -f4 | sort -h | uniq 1>>/home/kali/bash-scripts/output 2>/dev/null &
        done
        sleep 25
        echo "Wait for 25 seconds" 
        if [ -s /home/kali/bash-scripts/output ]
        then
                cat /home/kali/bash-scripts/output
        else
                echo "No hosts"
        fi
fi
