#!/bin/bash

hrishi()
{
echo "Enter the network"
read network 

echo "Enter the first host"
read first
echo "ENter second host"
read second
}

hrishi

if [ -z "$network" ] || [ -z "$first" ] || [ -z "$second" ]
then
        if [ -z "$network" ] && ([ -n "$first" ] && [ -n "$second" ])
        then
                echo "Network field cannot be empty"
        elif [ -z "$first" ] && ([ -n "$network" ] && [ -n "$second" ])
        then
                echo "first field cannot be empty"
        elif [ -z "$second" ] && ([ -n "$network" ] && [ -n "$first" ])
        then
                echo "second field cannot be empty"
        else
                echo "Fields cannot be left empty"
        fi
elif [ -n "$network" ] && [ -n "$first" ] && [ -n "$second" ]
then
        for ip in $(seq $first $second)
        do
                ping -c 1 $network.$ip | grep "64 bytes" | cut -d " " -f4 | sort -h | uniq & 2>/dev/null
        done
fi
------------------------------------------------------------------------------------------------------------------------------------------------
#!/bin/bash 

rm -rf /home/kali/bash-scripts/output 

echo "Enter the network portion: Example 192.1.1."
read network 

echo "Enter the host range: Part1"
read host1 

echo "Enter the host range: Part1"
read host2 

if [ -z "$network" ] || [ -z "$host1" ] || [ -z "$host2" ] 
then
        if [ \( -n "$network" -a -n "$host2" \) ]  && [ -z "$host1" ]
        then
                echo "host-1  is empty"
        elif [ \( -n "$network" -a -n "$host1" \) ]  && [ -z "$host2" ]
        then
                echo "host-2  is empty"
        elif [ \( -n "$host1" -a -n "$host2" \) ]  && [ -z "$network" ]
        then
                echo "Network portion is empty" 
        else
                echo "More field empty"
        fi
elif [ -n "$network" ] && [ -n "$host1" ] && [ -n "$host2" ]
then
        echo "*****************************"
        echo "Checking connectivity: $network$host1-$host2"
        for ip in $(seq $host1 $host2)
        do
        ping -c 1 $network$ip | grep -i "64 bytes" | cut -d " " -f4 | sort -h | uniq 1>>/home/kali/bash-scripts/output 2>/dev/null &
        done
        sleep 25
        echo "Wait for 25 seconds" 
        if [ -s /home/kali/bash-scripts/output ]
        then
                cat /home/kali/bash-scripts/output
        else
                echo "No hosts"
        fi
fi

------------------------------------------------------------------------------------------------------------------------------------------------

#!/bin/bash 

rm -rf /home/kali/bash-scripts/host_alive


echo "Enter the Network part. i.e 192.168.1."
read network 

echo "Enter the range: first host"
read first

echo "Enter the range: last host"
read last 

if [ -z "$network" ] || [ -z "$first" ] ||  [ -z "$last" ]
then
        if [ \( -n "$network"  -a  -n "$first" \) ] &&  [ -z "$last" ]
        then
                echo "Enter the range: Last host --> Field empty"
        elif [ \( -n "$network"  -a  -n "$last" \) ] &&  [ -z "$first" ]
        then
                echo "Enter the range: First host --> Field empty"
        elif [ \( -n "$first"  -a  -n "$last" \) ] &&  [ -z "$network" ]
        then
                echo "Enter the network --> Field empty"
        else
                echo "Empty fields not allowed"
        fi
elif [ -n "$network" ] && [ -n "$first" ] && [ -n "$last" ]
then
        echo "Looks like valid input"
        echo "************************************"
        sleep 1 
        for host_alive in $(seq $first $last)
        do
        ping -c 1 $network$host_alive | grep -i "64 bytes" | cut -d " " -f4 >> /home/kali/bash-scripts/host_alive &
done
        sleep 5
        if [ -s /home/kali/bash-scripts/host_alive ] 
        then
                cat /home/kali/bash-scripts/host_alive
        else
                echo "NO active host found" 

        fi
fi

