#!/bin/bash

echo "ENter first number"
read first

echo "Enter second number"
read second 

if [ -n "$first" ] && [ -n "$second" ]
then
        if [ $first -eq $second ]
        then
                echo "Both numbers are equal"
        elif [ $first -gt $second ]
        then
                echo "First number is greater"
        else
                echo "Second number is greater"
        fi
elif [ -z "$first" ] || [ -z "$second" ]
then
        if [ -n "$first" ] && [ -z "$second" ]
        then
                echo "Second number field is empty"
        elif [ -z "$first" ] && [ -n "$second" ]
        then
                echo "First number field is empty"

        else
                echo "Both fields cannot be empty for further proceeding"
        fi
fi
