#!/bin/bash 


echo "Enter the website" 
read website

if [ -z "$website" ]
then
        echo "Field empty, Try again"
elif [ -n "$website" ]
then
        wget -q $website
        if [ -s /home/kali/bash-scripts/index.html ]
        then
                cat index.html | grep -i "href" | cut -d "/" -f3 | cut -d '"' -f1 | grep -i "mega" | sort | uniq > /home/kali/bash-scripts/sub-domains
                sleep 3
                        if [ -s /home/kali/bash-scripts/sub-domains ]
                        then
                                for ip_address in $(cat /home/kali/bash-scripts/sub-domains)
                                do
                                        echo "****************************"
                                        host $ip_address | cut -d " " -f1,4 > /home/kali/bash-scripts/output
                                        sleep 1
                                        cat /home/kali/bash-scripts/output
                                done
                        else
                                echo "File is emtp, nothing to do" 
                        fi
                else
                        echo "SOmething went wrong, try again"
                fi
        fi

rm -rf /home/kali/bash-scripts/index.html
rm -rf /home/kali/bash-scripts/sub-domains
rm -rf /home/kali/bash-scripts/output
---------------------------------------------------------------------------------------------------------------------------------------------
cat index.html  | grep -i href | cut -d "/" -f3 | cut -d '"' -f1| grep -i "megacorpone" | sort -h | uniq > megacorpone


#!/bin/bash


echo "Enter the file location"
read file 

if [ -z "$file" ]
then
        echo "File location empty, Try again later"
else
        if [ -n "$file" ]
        then
                if [ -s "$file" ]
                then
                        for ip in $(cat $file)
                        do
                                host $ip | grep -i "has address" | cut -d " " -f1,4
                                echo "**********************************"
                        done
                else
                        echo "Invalid file or file empty"
                fi
        fi
fi

