#!/bin/bash

echo "ENter the domain namie: NO hostname" 
read domain 

echo "Enter the hostname file"
read filepath 

if [ -z "$domain" ] || [ -z "$filepath" ]
then
        if [ -n "$domain" ] && [ -z "$filepath" ]
        then
                echo "Hostname field empty"
        elif [ -z "$domain" ] && [ -n "$filepath" ]
        then
                echo "Domain field empty"
        else
                echo "EMpty field not permitted"
        fi

elif [ -n "$domain" ] && [ -n "$filepath" ]
then
        if [ -s "$filepath" ]
        then
                for hosting in $(cat $filepath )
                do
                        host $hosting.$domain | cut -d " " -f1,4 | grep -i ".com"
                done
        else
                echo "INavlid file path"
        fi
fi
