#!/bin/bash


echo "***********Lookput: JavaScript Files**********"
echo "Enter the file location"
read filepath 

if [ -z "$filepath" ]
then
        echo "Field empty, Try again later" 
else
        if [ -n "$filepath" ]
        then
                if [ -s "$filepath" ]
                then
                        echo "******************************"
                        cat $filepath | cut -d "/" -f5 | cut -d " " -f1 | sort -h | uniq | grep -i ".js" 
                        echo "******************************"

                else
                        echo "File not found"
                fi
        else
                echo "Invalid Path"
        fi
fi
