#!/bin/bash
echo "Enter the network portion: subnet 24"
read network 

if [ -z "$network" ]
then
        echo "EMpty field not allowed"
elif [ -n "$network" ]
then
        for ip in $(seq 1 254)
        do
                host $network.$ip | grep ".com" | cut -d " " -f1,5 | cut -d "." -f1-4,6-9 
        done
fi
