#!/bin/bash

echo "Enter Absolute path of the file"
read path

if [ -n "$path" ] 
then
        if [ -e $path ]
        then
                if [ -r $path ]
                then
                        echo "Read permission"
                else
                        echo "NO read permission"
                fi
        fi
else
        echo "EMpty field is not allowd"
fi
