#!/bin/bash


echo "Enter first number" 
read first

echo "Enter second number"
read second 

if [ -z "$first" ] || [ -z "$second" ]
then
        if [ -z "$first" ] && [ -n "$second" ]
        then
                echo "First field is empty"
        elif [ -n "$first" ] && [ -z "$second" ]
        then
                echo "Second field is empty"
        else
                echo "Both fields are empty"
        fi
elif [ -n "$first" ] && [ -n "$second" ]
then
        echo "Checking whether the remainder is even or not"
        echo "First number:$first divided by second numner:$second"
        sleep 2
        if (( $first % $second == 0 ))
        then
                echo "Remainder is zero: Hence number is even"
        else
                echo "Remainder is not equalu to zero: Hence number is odd"
        fi

fi
