#!/bin/bash 

echo "Enter the first number"
read first

echo "Enter the second number"
read second 

if [ -z "$first" ] || [ -z "$second" ]
then
        if [ -n "$first" ] && [ -z "$second" ]
        then
                echo "Second number is empty"
        elif [ -z "$first" ] && [ -n "$second" ]
        then
                echo "First number is empty"
        else
                echo "Both number is empty"
        fi
elif [ -n "$first" ] && [ -n "$second" ]
then
        echo "*********************************"
        echo "Lets find out the remainder is odd or even"
        ans=$((first%second))
        if (( $ans % 2 == 0 ))
        then
                echo "Remainder is even"
        else
                echo "Remainder is odd"
        fi
fi

