#!/bin/bash 

echo "Enter the file path: Absolute Path"
read path

echo "Enter the file name"
read filename

if [ -z "$path" ] || [ -z "$filename" ]
then
        if [ -n "$path" ] && [ -z "$filename" ]
        then
                echo "Filename empty"
        elif [ -z "$path" ] && [ -n "$filename" ]
        then
                echo "Path empty"
        else
                echo "Both field empty"
        fi
elif [ -n "$path" ] && [ -n "$filename" ]
then
        if [ -e "$path$filename" ]
        then
                echo "******Checking its a soft link or not"
                sleep 1
                if [ -h "$path$filename" ]
                then
                        echo "Its a soft link"
                else
                        echo "Its not a soft link"
                fi
        fi
fi
