#!/bin/bash 

echo "Enter the username for avaliability" 
read username

if [ -z "$username" ]
then
        echo "Username field is empty"
elif [ -n "$username" ]
then
        cat /etc/passwd | cut -d ":" -f1 |  grep -w "$username" > /home/kali/bash-scripts/output
        if [ -s /home/kali/bash-scripts/output ]
        then
                echo "Username found"
                rm -rf /home/kali/bash-scripts/output
        else
                echo "Username not found"
                rm -rf /home/kali/bash-scripts/output
        fi
fi
--------------------------------------------------------------------------------------------------------------------------------------------------------------
#!/bin/bash

echo "Enter the username"
read username 

echo "ENter the file location"
read path

if [ -z "$username" ] || [ -z "$path" ]
then
        if [ -n "$username" ] && [ -z "$path" ]
        then
                echo "File location: Field is empty"
        elif [ -z "$username" ] && [ -n "$path" ]
        then
                echo "Username: Field is empty"
        else
                echo "both field empty" 
        fi
elif [ -n "$username" ] && [ -n "$path" ]
then
        if [ -s "$path" ]
        then
                cat /etc/passwd | cut -d ":"  -f1 > ./user_list
                cat ./user_list | grep $username > ./username 

                if [ -s ./username ]
                then
                        echo "$username found" 
                else
                        echo "Username not found" 
                fi
        fi
fi

rm -rf ./user_list
rm -rf ./username

--------------------------------------------------------------------------------------------------------------------------------------------------------------
#!/bin/bash

rm -rf /home/kali/bash-script/user-list
echo "Enter the username"
read username 

if [ -z "$username" ]
then
        echo "Field empty not permitted" 
else
        echo "*************************************"
        echo "Lets check the username" 
        cat /etc/passwd | cut -d ":" -f1 | grep -i "$username" > ./user-list
        if [ -s /home/kali/bash-scripts/user-list ]
        then
                echo "User already exists" 
        else
                echo "Username doesnt exist"
                echo "Would you like to create: Y or N"
                read answer
                if [ $answer == "Y" ]
                then
                        echo "******Creating new uswer**********"
                        echo "ENter the root password" 

                        sudo useradd -s /bin/bash test1

                        echo "*******Set password*********"
                        sudo passwd $username
                        echo "Acount ready to go"
                else
                        echo "Bye" 

                fi
        fi
fi
--------------------------------------------------------------------------------------------------------------------------------------------------------------
#!/bin/bash

echo "Enter the username"
read username 

if [ -z "$username" ]
then
        echo "Username field empty bye"
elif [ -n "$username" ]
then
        echo "*****Checking for the user********"
        echo "********Enter sudo password if asked *********"
        sudo cat /etc/passwd | cut -d ":" -f1 > ./user_list
        if [ -s /home/kali/bash-scripts/user_list ]
        then
                cat ./user_list | grep -i "$username" > user
                if [ -s /home/kali/bash-scripts/user ]
                then
                        echo "User found"
                else
                        echo "******User not found*******"
                        echo "Would you like to create one: Y or N"
                        read ans

                        if [ $ans == "Y" ]
                        then
                                echo "****Creating a new user*****"
                                echo "enter root password , if asked"
                                sudo useradd $username 
                                echo "**********User created*********"
                        else
                                echo "Bye, user not created"
                        fi
                fi
        else
                echo "File do no exit"
        fi
else
        echo "Something is wrong"
fi
rm -rf ./user_list
rm -rf ./user

