#!/bin/bash 

hrishi(){
echo "Enter username"
read username

echo "ENter password"
read password 
}
hrishi

incorrect(){
count=0
while ([ "$username" != "admin" ] && [ "$password" != "password" ]) && [ "$count" -lt 3 ]
        do
                hrishi
                ((count++))
                if [ "$username" == "admin" ] && [ "$password" == "password" ]
                then
                        echo "Loin sucess"
                else
                        continue
                fi
        done



}
if [ -z "$username" ] || [ -z "$password" ]
then
        if [ -n "$username"  ] && [ -z "$password" ]
        then
                echo "Password field empty"
        elif [ -z "$username"  ] && [ -n "$password" ]
        then
                echo "Username field empty"
        else
                echo "BOth field empty"

        fi
elif [ -n "$username" ] && [ -n "$password" ]
then
        if [ "$username" == "admin" ] && [ "$password" == "password" ]
        then
                echo "LOgin succcess"
        else
                incorrect
        fi

fi
