#!/bin/bash 

hrishi(){
echo "Enter username"
read username

echo "ENter password"
read password 
}
hrishi

incorrect(){
count=0
while ([ "$username" != "admin" ] && [ "$password" != "password" ]) && [ "$count" -lt 3 ]
        do
                hrishi
                ((count++))
                if [ "$username" == "admin" ] && [ "$password" == "password" ]
                then
                        echo "Loin sucess"
                else
                        continue
                fi
        done



}
if [ -z "$username" ] || [ -z "$password" ]
then
        if [ -n "$username"  ] && [ -z "$password" ]
        then
                echo "Password field empty"
        elif [ -z "$username"  ] && [ -n "$password" ]
        then
                echo "Username field empty"
        else
                echo "BOth field empty"

        fi
elif [ -n "$username" ] && [ -n "$password" ]
then
        if [ "$username" == "admin" ] && [ "$password" == "password" ]
        then
                echo "LOgin succcess"
        else
                incorrect
        fi

fi

-------------------------------------------------------------------------------------------------------------------------------
#!/bin/bash

hrishi ()
{
        echo "Enter username"
        read username 

        echo "Enter password"
        read password
}
hrishi

if [ -z "$username" ] || [ -z "$password" ]
then
        if [ -z "$username" ] && [ -n "$password" ]
        then
                echo "USername field is empty"
        elif [ -n "$username" ] && [ -z "$password" ]
        then
                echo "Password field is empty"
        else
                echo "Username and password field empty"
        fi
elif [ -n "$username" ] && [ -n "$password" ]
then
        if [ "$username" == "admin" ] && [ "$password" == "password" ]
        then
                echo "Login Success "


        elif [ "$username" != "admin" ] || [ "$password" != "password" ]
        then
                count=1
        while ([ "$username" != "admin" ] && [ "$password" != "password" ]) & [ $count -le 3 ]
        do
                hrishi
                if [ "$username" == "admin" ] && [ "$password" == "password" ]
                then
                        echo "Login Success "
                        break
                else
                        ((count++))
                        continue
                fi
        done
        fi
fi

