#!/bin/bash

a=10
echo $a

echo "*************************************"
b="hrishi"
echo $b

echo "*************************************"
c=$(date)
echo $c
echo "*************************************"
d=$(uptime | cut -d " " -f2 )
echo $d
echo "*************************************"
echo "Username which is currently logged in: $USER"
echo "*************************************"
echo "Primary group of the logged-in user is: $(id $USER)"
echo "*************************************"
