#!/bin/bash


echo "Enter the first number"
read first

echo "Enter second number"
read second 


if [ -z "$first" ] ||  [ -z "$second" ] 
then
        if [ -n "$first" ] &&  [ -z "$second" ] 
        then
                echo "Second number field is empty"
        elif [ -z "$first" ] &&  [ -n "$second" ] 
        then
                echo "First number field is empty"
        else
                echo "Both field empty"
        fi
elif [ -n "$first" ] &&  [ -n "$second" ] 
then
        ans=$((first*second))
        while [ $ans -lt 100 ]
        do
                ans=$((first*second))
                if [ $ans == 50 ]
                then
                        ((second++))
                        continue
                else
                        ans=$((first*second))
                        echo "Multiplication of $first and $second is: $ans"
                        ((second++))

                fi
        done
fi
