#!/bin/bash

echo "Enter first number"
read first

echo "Enter second number"
read second 

if [ -n "$first" ] && [ -n "$second" ]
then
        while [ $first -lt $second ]
        do
                echo "First number is $first"
                ((first=first+1))
                if [ $first -eq 12 ]
                then
                        continue
                else
                        echo "New number is: $first"
                        echo "********************************"
                fi
        done


elif [ -z "$first" ] || [ -z "$second" ]
then
        if [ -n "$first" ] && [ -z "$second" ]
        then
                echo "Second number field is empty"
        else
                echo "First number field is empty"
        fi
else
        echo "Something is wrong with input"
fi
