#!/bin/bash

echo "Enter the first number"
read first

echo "Enter the second number"
read second 

if [ -n "$first" ] && [ -n "$second" ]
then
        while [ $first -le $second ]
        do
                echo "First number is: $first"
                ((first=first+1))
                if [ $first  -le $second ]
                then
                        echo "New first number is $first"
                else
                        echo "Second number is equal or greater than first"
                        break
                fi

        done
elif [ -z "$first" ] && [ -z "$second" ]
then
        echo "Both field is empty"
elif [ -z "$first" ] || [ -z "$second" ]
then
        if [ -n "$first" ] && [ -z "$second" ]
        then
                echo "Second number field empty"
        elif [ -z "$first" ] && [ -n "$second" ]
        then
                echo "First number field empty"
        fi
else
        echo "Input might be invalid" 
fi



----------------------------------------------------------------------------------------------------------------------------------------------------------------
#!/bin/bash

echo "Enter the first number"
read first

echo "Enter the second number"
read second 

if [ -z "$first" ] || [ -z "$second" ]
then
        if [ -z "$first" ] && [ -z "$second" ]
        then
                echo "First and Second field cannot be empty"
        elif [ -n "$first" ] && [ -z "$second" ]
        then
                echo "Second field cannot be empty"
        else
                echo "First field cannot be empty"
        fi
elif [ -n "$first" ] && [ -n "$second" ]
then
        echo "******************************"
        echo "First number is : $first"
        echo "Second number is : $second"
        echo "******************************"
        sleep 4
        if [ $first -le $second ]
        then
                if [ $first -eq $second ]
                then
                        echo "First number is equal than second"
                        echo "Nothing to do"
                        echo "***********************************"
                else
                        echo "First Number: $first"
                        echo "Second number: $second"
                        echo "**********************************"
                        while [ $first -lt $second ]
                        do
                                ((first=first+1))
                                echo "New NUmber is: $first"
                        done
                fi
        fi
else
        echo "Invalid Input"
fi

