#!/bin/bash

#function asking user input
hrishi()
{
echo "Enter the first number"
read first

echo "ENter second number"
read second

}

hrishi

#Checking user input
if [ -z "$first" ] || [ -z "$second" ]
then
        if [ -z "$first" ] && [ -n "$second" ]
        then
                echo "First field cannot be empty"
        elif [ -n "$first" ] && [ -z "$second" ]
        then
                echo "Second field cannot be empty"
        else
                echo "Both field cannot be empty"
        fi
# user input
elif [ -n "$first" ] && [ -n "$second" ]
then
        if [ $first -lt $second ]
        then
                echo "*****************************"
                echo "COngrats, first number is smaller than second"
                echo "*****************************"
                ans=0
                while [ $ans -lt 50 ]
                do
                        ans=$((first * second))
                        echo "Hello: $first * $second = $ans" 
                        ((second++))
                done
        else
                echo "Second number is smaller"
                echo "Quit"
        fi
fi
----------------------------------------------------------------------------------------------------------------------------------
#!/bin/bash

hrishi(){
echo "Enter the first"
read first

echo "Enter second number"
read second 
}
operation(){
        ans=0
while [ $ans -lt 100 ] && [ $ans -ne 20 ] 
do
        echo "*****************************"
        ans=$((first * second))
        echo "First number is: $first"
        echo "Second number is $second"
        echo "Multiplication answer is: $ans"
        ((second++))
done
}
count=1
while [ $count -lt 3 ]
do
        hrishi
        if [ -z "$first" ] || [ -z "$second" ]
        then
                if [ -n "$first" ] && [ -z "$second" ]
                then
                        echo "Second number is empty"
                elif [ -z "$first" ] && [ -n "$second" ]
                then
                        echo "First number is empty"
                else
                        echo "Both numbers are empty"
                fi
        elif [ -n "$first" ] && [ -n "$second" ]
        then
                operation
        fi
        break
done

